version: "3"

volumes:
  node_modules:
  cache:
services:
  npm-command:
    ipc: host
    build:
      context: .
      dockerfile: Dockerfile
    command: npm i
    ports:
      - "3000:3000"
    volumes:
      - ./cypress:/cypress
      - ./src:/src
      - ./static:/static
      - node_modules:/node_modules
      - cache:/root/.cache/
